In [8]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [9]:
sentence = [
    'I love my Dog!',
    'I love my cat.',
    'You love my dog!',
    'Do you think my dog is amazing?'
]

In [10]:
tokenizer = Tokenizer(num_words=100, oov_token=r"<OOV>")
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
print(word_index)

{'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}


In [11]:
sequences = tokenizer.texts_to_sequences(sentence)
print(sequences)

[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]


In [12]:
padded = pad_sequences(sequences, maxlen=5, padding='pre', truncating='post')
print(padded)


[[0 5 3 2 4]
 [0 5 3 2 7]
 [0 6 3 2 4]
 [8 6 9 2 4]]


In [14]:
from tensorflow.keras import datasets
print(vars(datasets.))


{'__name__': 'tensorflow_core.keras.datasets', '__doc__': 'Public API for tf.keras.datasets namespace.\n', '__package__': 'tensorflow_core.keras.datasets', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x000001A82389E320>, '__spec__': ModuleSpec(name='tensorflow_core.keras.datasets', loader=<_frozen_importlib_external.SourceFileLoader object at 0x000001A82389E320>, origin='c:\\users\\mhasa\\google drive\\tutorial corner\\pyth\\pycharm projects\\naturallangprocessing\\venv\\lib\\site-packages\\tensorflow_core\\python\\keras\\api\\_v2\\keras\\datasets\\__init__.py', submodule_search_locations=['c:\\users\\mhasa\\google drive\\tutorial corner\\pyth\\pycharm projects\\naturallangprocessing\\venv\\lib\\site-packages\\tensorflow_core\\python\\keras\\api\\_v2\\keras\\datasets']), '__path__': ['c:\\users\\mhasa\\google drive\\tutorial corner\\pyth\\pycharm projects\\naturallangprocessing\\venv\\lib\\site-packages\\tensorflow_core\\python\\keras\\api\\_v2\\keras\\datasets