In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

In [3]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]]).to(device)

In [4]:
tensor.shape

torch.Size([2, 3])

In [7]:
tensor.view(-1,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [9]:
torch.exp(tensor)

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [11]:
torch.exp(tensor) / torch.sum(torch.exp(tensor), dim=1)

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])

In [16]:
torch.sum(torch.exp(tensor), dim=1).numpy().shape

(2,)