In [1]:
import sys, os, json
import numpy as np
import pandas as pd
import seaborn as sns
import argparse, progressbar
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
import matplotlib.axes._axes as axes
sns.set()

In [2]:
import torch
import torchvision
from torch import nn
from torch import optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms, models

In [3]:
v = np.array([2, -1])

In [4]:
v.shape

(2,)

In [5]:
v3 = np.array([
    [2],
    [5],
    [4],
    [7]
])

In [6]:
v3.shape

(4, 1)

In [7]:
v4 = v3.T

In [8]:
v4.shape

(1, 4)

In [9]:
v4

array([[2, 5, 4, 7]])

In [10]:
hidden_state = torch.zeros(2)
hidden_state

tensor([0., 0.])

In [11]:
hidden_state.shape


torch.Size([2])

In [12]:
hidden_state_np = np.zeros(2)
hidden_state_np

array([0., 0.])

In [13]:
hidden_state_np.shape

(2,)

In [45]:
n_features = 3
hidden_dim = 2

torch.manual_seed(19)
rnn_cell = nn.RNNCell(input_size=n_features,
                      hidden_size=hidden_dim)
rnn_state = rnn_cell.state_dict()
rnn_state

OrderedDict([('weight_ih',
              tensor([[ 0.6627, -0.4245,  0.5373],
                      [ 0.2294, -0.4015, -0.5385]])),
             ('weight_hh',
              tensor([[-0.1956, -0.6835],
                      [ 0.4954,  0.6533]])),
             ('bias_ih', tensor([-0.3565, -0.2904])),
             ('bias_hh', tensor([-0.6701, -0.5811]))])

In [46]:
rnn_state['weight_ih'].shape

torch.Size([2, 3])

In [47]:
linear_input = nn.Linear(3, 2)
linear_input.state_dict()

OrderedDict([('weight',
              tensor([[-0.0138, -0.4781,  0.0946],
                      [-0.5697,  0.2646, -0.0803]])),
             ('bias', tensor([-0.2582, -0.1758]))])

In [48]:
X = torch.tensor(data=[[1.0349, 0.9661, 0.566],
                       [0.8055, -0.9169, 0.566],
                       [-0.8251, -0.9499, 0.566],
                       [-0.8670, 0.9342, 0.566]])

In [49]:
X.shape

torch.Size([4, 3])

In [50]:
X[0:1].shape

torch.Size([1, 3])

In [51]:
X[0]

tensor([1.0349, 0.9661, 0.5660])

In [52]:
tx = linear_input(X[0:1])
tx

tensor([[-0.6809, -0.5552]], grad_fn=<AddmmBackward0>)

In [53]:
Wih = linear_input.state_dict()['weight']
bias = linear_input.state_dict()['bias']

In [54]:
Wih.shape

torch.Size([2, 3])

In [55]:
bias.shape

torch.Size([2])

In [57]:
result = torch.mm(X[0:1], Wih.T)

In [58]:
result.shape

torch.Size([1, 2])

In [59]:
final_result = result + bias
final_result

tensor([[-0.6809, -0.5552]])